version: '3.4'

services:

  client:
    command: sh /code/start.sh
    build:
      context: .
      dockerfile: services/client/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./services/client:/code
      - /services/client/application/static:/code/application/static
    environment:
      DEBUG: 1
      URL: http://client:8000/
      ALLOWED_HOSTS: "*"
      DB_NAME: 'postgres'
      DB_USER: 'postgres'
      DB_PASS: 'postgres'
      DB_ADDR: 'db'
      DB_PORT: '5432'
      SECRET_KEY: 'dcj6)a_mmj+_r=@02e9hf_%*o4u9*zodaj=sr!y5z0133bf27^'

  location:
    command: sh /code/start.sh
    build:
      context: .
      dockerfile: services/location/Dockerfile
    ports:
      - "5050:5050"
    volumes:
      - ./services/location:/code
    environment:
      URL: http://location:5050/
      DB_NAME: 'postgres'
      DB_USER: 'postgres'
      DB_PASS: 'postgres'
      DB_ADDR: 'db'
      DB_PORT: '5432'

  clustering:
    command: sh /code/start.sh
    build:
      context: .
      dockerfile: services/clustering/Dockerfile
    ports:
      - "6060:6060"
    volumes:
      - ./services/clustering:/code
    environment:
      URL: http://clustering:6060/

  routering:
    command: sh /code/start.sh
    build:
      context: .
      dockerfile: services/routering/Dockerfile
    ports:
      - "7070:7070"
    volumes:
      - ./services/routering:/code
    environment:
      URL: http://routering:7070/

  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - hermex-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nginx:
    build:
      dockerfile: services/nginx/Dockerfile
      context: .
    ports:
    - "80:80"
    depends_on:
    - client
    volumes:
      - ./services/client/application/static:/var/www/static

volumes:
  hermex-data: