# Generated by Django 2.2.5 on 2019-09-19 21:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('cnpj', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=-23.554189)),
                ('longitude', models.FloatField(default=-46.662206)),
            ],
            options={
                'ordering': ['latitude', 'longitude'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=127)),
                ('street_number', models.IntegerField(blank=True)),
                ('info', models.CharField(max_length=127)),
                ('neighborhood', models.CharField(blank=True, max_length=127, null=True)),
                ('city', models.CharField(blank=True, max_length=127, null=True)),
                ('state', models.CharField(blank=True, max_length=3, null=True)),
                ('country', models.CharField(blank=True, max_length=3, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_coordinates', to='application.Coordinates')),
            ],
            options={
                'ordering': ['coordinates'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.IntegerField(choices=[(0, 'passenger'), (1, 'driver'), (2, 'manager'), (3, 'all-access')], default=0)),
                ('value', models.CharField(blank=True, max_length=511, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry', models.DateTimeField()),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('model', models.CharField(max_length=127)),
                ('license_plate', models.CharField(max_length=15)),
                ('capacity', models.IntegerField(default=13)),
                ('status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'maintenance')], default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_company', to='application.Company')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=127, null=True)),
                ('type', models.IntegerField(choices=[(0, 'other'), (1, 'totem'), (2, 'roof')], default=0)),
                ('sidewalk', models.IntegerField(choices=[(0, 'other'), (1, 'sidewalk'), (2, 'lane')], default=0)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_address', to='application.Location')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stop_company', to='application.Company')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('cpf', models.CharField(max_length=15)),
                ('birthday', models.DateField(default=datetime.date(1997, 5, 22))),
                ('phone', models.CharField(max_length=15)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('entry_time', models.TimeField(default=django.utils.timezone.now)),
                ('exit_time', models.TimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'vacation')], default=True)),
                ('password', models.CharField(max_length=1023)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_address', to='application.Location')),
                ('home_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_home_address', to='application.Location')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('cpf', models.CharField(max_length=15)),
                ('birthday', models.DateField(default=datetime.date(1997, 5, 22))),
                ('phone', models.CharField(max_length=15)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'vacation')], default=0)),
                ('password', models.CharField(max_length=1023)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_company', to='application.Company')),
                ('home_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_home_address', to='application.Location')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=127)),
                ('cpf', models.CharField(max_length=15)),
                ('birthday', models.DateField(default=datetime.date(1997, 5, 22))),
                ('phone', models.CharField(max_length=15)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('cnh', models.CharField(max_length=15)),
                ('status', models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'vacation')], default=0)),
                ('home_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_home_address', to='application.Location')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_address', to='application.Location'),
        ),
    ]
