# Generated by Django 2.2.5 on 2019-09-23 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20190922_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='geometry',
        ),
        migrations.CreateModel(
            name='Geocoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Coordinates')),
                ('geometry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Geometry')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
