from application.models.company import Company
from application.models.coordinates import Coordinates
from application.models.driver import Driver
from application.models.location import Location
from application.models.manager import Manager
from application.models.passenger import Passenger
from application.models.person import Person
from application.models.stop import Stop
from application.models.token import Token
from application.models.vehicle import Vehicle